# Switch database to an in-memory test database
spring.datasource.url=jdbc:oracle:thin:@fsktmdbora.upm.edu.my:1521:FSKTM
spring.datasource.username=E228142
spring.datasource.password=228142

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Match SQL styling behaviors
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Turn on a web dashboard to see your data at http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true

