# Switch database to an in-memory test database
spring.datasource.url=jdbc:h2:mem:dentalhub;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Match SQL styling behaviors
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Turn on a web dashboard to see your data at http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true