BEGIN
EXECUTE IMMEDIATE 'DROP TABLE PATIENT CASCADE CONSTRAINTS';
EXCEPTION
 WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
       RAISE;
END IF;
END;
/


CREATE TABLE PATIENT (
                         patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         full_name VARCHAR2(100) NOT NULL,
                         email VARCHAR2(100) UNIQUE NOT NULL,
                         phone_number VARCHAR2(20) NOT NULL,
                         password VARCHAR2(100) NOT NULL
);
